// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OpieAndAnthonyRadioShow.Data;
using System;

namespace OpieAndAnthonyRadioShow.Data.Migrations
{
    [DbContext(typeof(OpieAndAnthonyRadioShowDbContext))]
    partial class OpieAndAnthonyRadioShowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OpieAndAnthonyRadioShow.Data.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Occupation");

                    b.Property<int?>("RadioShowId");

                    b.HasKey("Id");

                    b.HasIndex("RadioShowId");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("OpieAndAnthonyRadioShow.Data.Models.RadioShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AirTime");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("RadioShows");
                });

            modelBuilder.Entity("OpieAndAnthonyRadioShow.Data.Models.RadioShowTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("RadioShowId");

                    b.HasKey("Id");

                    b.HasIndex("RadioShowId");

                    b.ToTable("RadioShowTags");
                });

            modelBuilder.Entity("OpieAndAnthonyRadioShow.Data.Models.Guest", b =>
                {
                    b.HasOne("OpieAndAnthonyRadioShow.Data.Models.RadioShow")
                        .WithMany("Guests")
                        .HasForeignKey("RadioShowId");
                });

            modelBuilder.Entity("OpieAndAnthonyRadioShow.Data.Models.RadioShowTag", b =>
                {
                    b.HasOne("OpieAndAnthonyRadioShow.Data.Models.RadioShow")
                        .WithMany("Tags")
                        .HasForeignKey("RadioShowId");
                });
#pragma warning restore 612, 618
        }
    }
}
